### ISSUE TITLE
Undefined arg coming from socket.on('new-vote-on-message'    ...      on thumbs up (value 1)

### ISSUE THREAD

**Issue by odgaard** [Viestinta/viestinta#49]
![image](https://cloud.githubusercontent.com/assets/23553119/24774480/55a0367a-1b19-11e7-8670-a3c05b49cbb2.png)

**Comment by weedle1912** [comment]
![issue49](https://cloud.githubusercontent.com/assets/15259792/24788880/3ed05d24-1b70-11e7-9167-ec5a7a780f80.png)

Added line (in server/app.js) that was lost in handeling of merge conflicts. 

This fixes the 'Unhandled rejection TypeError', as this value now is defined and sent when voting, but it still seems incomplete at server side, as it is not mentioned in e.g. createMessage(...) in server/database/controllers/messages.js

**Comment by odgaard** [comment]
The id is missing from the createMessage in the controller because the id is simply auto-generated as part of an integer auto-increment counter. The fix above is correct, and more changes shouldn't be necessary. Thank you
