### ISSUE TITLE
Animation when you click on messages, but nothing happens

### ISSUE THREAD

**Issue by teatimes** [Viestinta/viestinta#58]
Should remove the animation

**Comment by teatimes** [comment]
Fixed in branch Issues

**Comment by weedle1912** [comment]
<ListItem> component has property _disabled_, so the issue is better handled by editing this property in the return- statement of the render() function in Message.js like this:
```
<ListItem
   style={styles.listItem}
   primaryText={this.props.text}
   secondaryText={this.props.isAdmin ? footerAdmin : footer}
   disabled={true}
/>
```
(For better code quality).
