### ISSUE TITLE
initial docker-compose up is unable to connect to database

### ISSUE THREAD

**Issue by odgaard** [Viestinta/viestinta#9]
The first time "`sudo docker-compose up`" is called, the call on node app.js will give the following error:
`Unable to connect to the database: { SequelizeConnectionRefusedError: connect ECONNREFUSED 172.18.0.2:5432`

The next time the command is called the database connects properly. 

This is probably due to the ordering of the commands in the docker files.

**Comment by oleast** [comment]
Ganske sikker på at dette kommer av at det tar tid å sette opp databasen første gang. Er tydeligvis ikke stort mye som kan gjøres med det utenom å hacke det til å vente på at porten er klar. Kan kanskje virke å legge til `depends_on: postgres` i nodejs containeren?

**Comment by odgaard** [comment]
La til depends_on: i nodejs containeren ja, men det førte bare til at de ble startet i riktig rekkefølge, men da ble oppstarten tilnærmet samtidig, fordi de venter ikke på at den andre skal bli "ferdig". Dermed lagte jeg et bash script som venter i 8 sek istedenfor, før node app.js starter opp.
